### ISSUE TITLE
`spec.ip` missing for use by jobs

### ISSUE THREAD

**Issue by andreas-kupries** [cloudfoundry-incubator/cf-operator#421]
Bringing up the trafficcontroller job of the log-api instance group currently fails because
it apparently needs a proper value for `spec.ip`.

The error message `panic: Unable to load config: Need IP address for access logging` in the logs can be traced to `TRAFFIC_CONTROLLER_IP: "<%= spec.ip %>"` in `bpm.yml.erb` in the job.

I have further confirmed that the resolved bosh manifest going into `RenderJobTemplates` found in `render_job_tmpls_.go` has the IP information set to the empty string, for all instance groups and all jobs.

Example:

```
   properties:
      bosh_containerization:
        consumes: {}
        instances:
        - address: scf-nats-0.scf.svc.cluster.local
          az: z1
          id: nats-0-nats
          index: 0
          instance: 0
          name: nats-nats
          network: {}
          ip: ""
```

Given my talks with Thulio I believe that this problem has to be fixed in the template rendering for the pods/jobs, and cannot be fixed during data gathering, as the IP for the pod (or the cluster service ip for the pods service ?) are dynamic and not known at gathering time.
