### ISSUE TITLE
Missing instance.id in link consumes

### ISSUE THREAD

**Issue by edwardstudy** [cloudfoundry-incubator/cf-operator#638]
Hi, we are deploying autoscaler over cf-operator and get consumes info which missed `instance.id`:

```
quarks:
  consumes:
    metricsserver:
      address: autoscaler-asmetrics
      instances:
      - address: autoscaler-asmetrics-0
        az: ""
        bootstrap: true
        index: 0
        instance: 0
        name: asmetrics-metricsserver
        networks: null
      - address: autoscaler-asmetrics-1
        az: ""
        bootstrap: false
        index: 1
        instance: 1
        name: asmetrics-metricsserver
        networks: null
```

It caused rendering wrong template which could not get the right index because `i.id` is empty(render job set spec.id as pod name):

https://github.com/cloudfoundry/app-autoscaler-release/blob/677fdfce9c8a151d384c884a4acec394b1bb6f62/jobs/metricsserver/templates/metricsserver.yml.erb#L27

The root cause is that `instance-group` cmd could not set right instance id for each group:
https://github.com/cloudfoundry-incubator/cf-operator/blob/f46d1ae93649f65daa7ef0e79831f65fd4587655/pkg/bosh/manifest/cmd_instance_group_resolver.go#L229-L236
