### ISSUE TITLE
bpm job crashes with null pointer

### ISSUE THREAD

**Issue by kramerul** [cloudfoundry-incubator/cf-operator#645]
With the following BOSHDeploment ( loggregator_agent without nats properites)

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-manifest
data:
  manifest: |
    ---
    name: nats-manifest
    update:
      serial: false
    releases:
    - name: nats
      version: "26"
      url: docker.io/cfcontainerization
      stemcell:
        os: opensuse-42.3
        version: 30.g9c91e77-30.80-7.0.0_257.gb97ced55
    - name: loggregator-agent
      url: docker.io/cfcontainerization
      version: "3.9"
    instance_groups:
    - name: nats
      jobs:
      - name: nats
        release: nats
        properties:
          nats:
            user: admin
            password: 123456
          quarks:
            ports:
            - name: "nats1"
              protocol: "TCP"
              internal: 4222
            - name: "nats1-routes"
              protocol: TCP
              internal: 4223
    - name: loggregator_agent
      release: loggregator-agent
      update:
        serial: true
        properties:
          quarks:
            ports:
---
apiVersion: fissile.cloudfoundry.org/v1alpha1
kind: BOSHDeployment
metadata:
  name: nats-deployment
spec:
  manifest:
    name: nats-manifest
    type: configmap
```

the bpm job crashes with

```
2019/10/15 15:02:03 recovered in f: runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0xc000499730, 0x14f8540, 0x257d1b0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
code.cloudfoundry.org/cf-operator/cmd/internal.glob..func1.1(0xc000499da8)
	/go/src/code.cloudfoundry.org/cf-operator/cmd/internal/bpm_configs.go:35 +0x141
panic(0x14f8540, 0x257d1b0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
code.cloudfoundry.org/cf-operator/pkg/bosh/manifest.(*InstanceGroupResolver).BPMConfigs(0xc0004b9b00, 0x16, 0xc000042046, 0xb)
	/go/src/code.cloudfoundry.org/cf-operator/pkg/bosh/manifest/cmd_instance_group_resolver.go:56 +0x108
code.cloudfoundry.org/cf-operator/cmd/internal.glob..func1(0x25898a0, 0x25b9728, 0x0, 0x0, 0x0, 0x0)
	/go/src/code.cloudfoundry.org/cf-operator/cmd/internal/bpm_configs.go:96 +0x3cd
github.com/spf13/cobra.(*Command).execute(0x25898a0, 0xc00003a1a0, 0x0, 0x0, 0x25898a0, 0xc00003a1a0)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0x258a020, 0x405a0f, 0xc000088058, 0x0)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
code.cloudfoundry.org/cf-operator/cmd/internal.Execute()
	/go/src/code.cloudfoundry.org/cf-operator/cmd/internal/root.go:142 +0x2e
main.main()
	/go/src/code.cloudfoundry.org/cf-operator/cmd/cf-operator/main.go:6 +0x20
```

**Comment by c0d1ngm0nk3y** [comment]
If you add

```yaml
properties:
  bpm:
    enabled: true
```

to each job, at least this exception does not occur anymore. But this seems to be related to having several `instance_groups` and not `jobs`. I haven't understood it completely yet. I wonder why there are only `e2e-tests` with exactly one `instance_group`.
