### ISSUE TITLE
New variables added to the manifest don't get generated

### ISSUE THREAD

**Issue by f0rmiga** [cloudfoundry-incubator/cf-operator#733]
## The issue

While investigating the `rotate-cc-database-key` errand on kubecf (https://github.com/SUSE/kubecf/issues/203), I ended up creating a mechanism to add new variables: https://github.com/SUSE/kubecf/blob/44c9f5d280937682dde9c50d995662abe9a7f9dd/deploy/helm/kubecf/assets/operations/instance_groups/api.yaml#L46-L66.

The end result was:

```yaml
database_encryption:
  current_key_label: encryption_key_1
  keys:
    encryption_key_0: Tw2nYSfrUOUeKGz15S6YVRLwrKzmQrgHukNe0PpTDyVeLnRKmVeZlxh2ptNyiLeq
    encryption_key_1: ((encryption_key_1))
```

WIP: https://github.com/SUSE/kubecf/tree/f0rmiga/rotate-cc-database-key

I can see that the new variable was added to the `with-ops` manifest, but cf-operator didn't create a new secret for that.

## Expected behaviour

I expected that the variable would be created, and the `((encryption_key_1))` would be rendered to its value.
