### ISSUE TITLE
Changing the quarks property for a job using an ops-file didn't create missing services

### ISSUE THREAD

**Issue by f0rmiga** [cloudfoundry-incubator/cf-operator#734]
## The issue

Applying the following ops-file on an existing kubecf installation didn't create the credhub services:

```yaml
- type: replace
  path: /instance_groups/name=credhub/jobs/name=credhub/properties/quarks?
  value:
    ports:
    - name: service-broker
      protocol: TCP
      internal: &credhubServiceBrokerPort 8844
    run:
      healthcheck:
        credhub:
          readiness:
            httpGet:
              port: *credhubServiceBrokerPort
              path: /health
              scheme: HTTPS
```

## Expected behaviour

I'd expect that cf-operator created the service, or updated it if it existed before (in my case it didn't exist).
