### ISSUE TITLE
Specifying a new readiness probe using an ops-file doesn't recreate the pod

### ISSUE THREAD

**Issue by f0rmiga** [cloudfoundry-incubator/cf-operator#812]
On KubeCF, when I try to upgrade an existing installation to update a readiness probe, the pod doesn't get recreated.

**Comment by edwardstudy** [comment]
I tried to reproduce this issue. And desired manifest has added the proper item: `quarks.run.healthcheck`. But quarks job `ig` didn't create new version of IG. Maybe it was equal to older one.

**Comment by edwardstudy** [comment]
Opened a PR: https://github.com/cloudfoundry-incubator/cf-operator/pull/841

Hi, I examined the code changes thru this manifest to update:
https://github.com/cloudfoundry-incubator/cf-operator/blob/92f5724c205f4fc953cb4fb6d2da89e6fe81e86b/docs/examples/bosh-deployment/boshdeployment.yaml

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-manifest
data:
  manifest: |
    ---
    name: nats-deployment
    releases:
    - name: nats
      version: "26"
      url: docker.io/cfcontainerization
      stemcell:
        os: opensuse-42.3
        version: 30.g9c91e77-30.80-7.0.0_257.gb97ced55
    instance_groups:
    - name: nats
      instances: 1
      jobs:
      - name: nats
        release: nats
        properties:
          nats:
            user: admin
            password: ((nats_password))
          quarks:
            ports:
            - name: "nats"
              protocol: "TCP"
              internal: 4222
            - name: "nats-routes"
              protocol: TCP
              internal: 4223
            run:
              healthcheck:
                nats:
                  readiness:
                    exec:
                      command:
                      - "echo healthy"
```

I could see quarksStatefulset changed about readinessProbe:
```
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksStatefulSet
metadata:
...
  name: nats-deployment-nats
  namespace: staging
...
spec:
  template:
    spec:
        spec:
          containers:
          - name: nats-nats
            readinessProbe:
              exec:
                command:
                - echo healthy
```
