### ISSUE TITLE
Changing the readiness probe did not recreate the pod

### ISSUE THREAD

**Issue by f0rmiga** [cloudfoundry-incubator/cf-operator#857]
**Describe the bug**

While bumping the cf-deployment version on KubeCF, it was required to change one of the readiness probes for doppler. Switching from a `exec.command` to a `tcpSocket.port` didn't trigger a pod recreation, and I can assert that not even the QuarksStatefulSet got updated.

**To Reproduce**

Change the doppler readiness probe from:

```yaml
      healthcheck:
        doppler:
          readiness:
            exec:
              command: [curl, --fail, --head, --silent, http://localhost:14825/health]
```

to

```yaml
      healthcheck:
        doppler:
          readiness:
            tcpSocket:
              port: 3459
```

**Expected behavior**

I expected the readiness probe to be updated.

**Environment**
 - CF-Operator Version: v3.3.0-0.gf32b521e.
 - KubeCF v1.0.1-ish.
