### ISSUE TITLE
Operator does not delete obsolete qsts

### ISSUE THREAD

**Issue by mook-as** [cloudfoundry-incubator/cf-operator#877]
**Describe the bug**
When upgrading from cf-operator 3.x to 4.0.0, the obsolete QuarksStatefulSets (the old ones with prefixes) do not get deleted.

**To Reproduce**
1. Deploy [`kubecf@21802f2d`].
2. Checkout [`kubecf@0bbceef8`].
3. Update cf-operator with `bazel run //dev/cf_operator:apply`.
4. Update kubecf with `bazel run //dev/kubecf:apply`.

[`kubecf@21802f2d`]: https://github.com/cloudfoundry-incubator/kubecf/commit/21802f2d53457fa67e185e86349ab1a8ccfc0668
[`kubecf@0bbceef8`]: https://github.com/cloudfoundry-incubator/kubecf/pull/581/commits/0bbceef8fb9366973cc37b1e900a29aa4bcdd13f
Alternatively:
1. Deploy cf-operator `3.4.0+0.g0c173836`.
2. Deploy any BDPL.
3. Upgrade to cf-operator `4.0.0+1.g97d42f19`.
4. Re-deploy the same BDPL.

**Expected behaviour**
The old, prefixed pods are removed (e.g. `kubecf-api-0`).

**Actual behaviour**
Both the old and new pods exist (`api-0` + `kubecf-api-0`).

**Environment**
 - CF-Operator Version: `3.4.0+0.g0c173836` / `4.0.0+1.g97d42f19`.
 - Kubernetes: minikube v1.6.2 + kube 1.15.6
 - [`kubecf@21802f2d`] / [`kubecf@0bbceef8`]

**Additional context**
This is of course only when upgrading.

The old qsts has the proper labels:
```yaml
kind: QuarksStatefulSet
metadata:
  labels:
    quarks.cloudfoundry.org/deployment-name: kubecf
    quarks.cloudfoundry.org/deployment-version: "1"
    quarks.cloudfoundry.org/instance-group-name: api
  ownerReferences:
  - apiVersion: quarks.cloudfoundry.org/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: BOSHDeployment
    name: kubecf
    uid: ac1562fc-510c-4e15-993f-deb39ee61dcf
```
That appears to match the bdpl:
```yaml
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: BOSHDeployment
metadata:
  generation: 2
  labels:
    app.kubernetes.io/instance: kubecf
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubecf
    app.kubernetes.io/version: v0.0.0-0bbceef
    helm.sh/chart: kubecf-v0.0.0-0bbceef
  name: kubecf
  namespace: kubecf
  uid: ac1562fc-510c-4e15-993f-deb39ee61dcf
```

I assume this would be similar when upgrading between two versions of a bdpl (using the same operator), if the instance groups have changed?
